### ISSUE TITLE
Evaluation Set

### ISSUE THREAD

**Issue by fuqichen1998** [zhengqili/Neural-Scene-Flow-Fields#33]
Hi,

I found the `evaluation.py` actually use the training images. Could you please share how to get the exact number in Table 3 of your paper. More specifically, how to know which are 

> the remaining 11 held-out images per time instance for evaluation

?

**Comment by zhengqili** [comment]
In line 295: https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/d4001759a39b056c95d8bc22da34b10b4fb85afb/nsff_exp/evaluation.py#L295

We skipped the training image by checking if image index % 12 is same as camera index, since there are 12 cameras in total and we generate training images in circular fashion

**Comment by fuqichen1998** [comment]
Got it, thanks very much for your quick reply!
